sudo: required
services:
    - docker

before_install:
    - docker build -t 1after/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true 1after/react-test npm test -- --coverage

after_success:
    - docker build -t 1after/multi-client ./client 
    - docker build -t 1after/multi-nginx ./ngnix
    - docker build -t 1after/multi-server ./server
    - docker build -t 1after/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push 1after/multi-client
    - docker push 1after/multi-nginx
    - docker push 1after/multi-server
    - docker push 1after/multi-worker
deploy:
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-957826690966"
    bucket_path: "dokcer-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY     
    secret_access_key: $AWS_SECRET_KEY